version: "3"

services:
  builder:
    build:
      context: builder
    image: eosio/builder

  nodgeneosd:
    build:
      context: .
    image: eosio/eos
    command: /opt/eosio/bin/nodgeneosd.sh --data-dir /opt/eosio/bin/data-dir
    hostname: nodgeneosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - nodgeneos-data-volume:/opt/eosio/bin/data-dir

  kgeneosd:
    image: eosio/eos
    command: /opt/eosio/bin/kgeneosd --wallet-dir /opt/eosio/bin/data-dir
    hostname: kgeneosd
    links:
      - nodgeneosd
    volumes:
      - kgeneosd-data-volume:/opt/eosio/bin/data-dir

volumes:
  nodgeneos-data-volume:
    external: true
  kgeneosd-data-volume:
    external: true
