version: "3"

services:
  nodgeneosd:
    image: eosio/eos:v1.0.7
    command: /opt/eosio/bin/nodgeneosd.sh --data-dir /opt/eosio/bin/data-dir -e
    hostname: nodgeneosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - nodgeneos-data-volume:/opt/eosio/bin/data-dir

  kgeneosd:
    image: eosio/eos:v1.0.7
    command: /opt/eosio/bin/kgeneosd --wallet-dir /opt/eosio/bin/data-dir --http-server-address=127.0.0.1:8900
    hostname: kgeneosd
    links:
      - nodgeneosd
    volumes:
      - kgeneosd-data-volume:/opt/eosio/bin/data-dir

volumes:
 nodgeneos-data-volume:
   external: true
 kgeneosd-data-volume:
   external: true
